name: datacrurl
on:
  schedule:
   #- cron: "0 1 * * *"
   - cron: "4,14,24,34,44,54 * * * *"
  workflow_dispatch:
 
#xxx
jobs:
  build:
    runs-on: ubuntu-18.04 #ubuntu-latest
    steps:        
     - name: Download zip
       env:
          url: ${{ secrets.crurl }}
       run: |
          echo Download dll
          wget -q --output-document=finalzip.zip $url 
          echo unzip..........
          unzip finalzip.zip -d finalzip
          sudo chmod -R +X finalzip 
          cd finalzip
          dotnet CrawlData.dll
